### ISSUE TITLE
Results visualization

### ISSUE THREAD

**Issue by colaber2** [nicehuster/SymPoint#4]
I would like to see the visual results. However, it seems that the `test.py` file has a section for saving results but it's not implemented yet. Do you have any advice on how to show the images with detections?

Thank you in advance, and I really appreciate your work.

**Comment by chunibyo-wly** [comment]
hello, can you try this? I'm not sure if it's right.
It will estimate the semantic id and instance id, and change the color of corresponding path in svg.

```python
import argparse
import glob
from itertools import chain
import json
import math
import os
import re
import time
import xml.etree.ElementTree as ET
from collections import defaultdict

import mmcv
import numpy as np
import torch
from tqdm import tqdm
import yaml
from munch import Munch
from svgpathtools import parse_path

from svgnet.evaluation.point_wise_eval import InstanceEval
from svgnet.model.svgnet import SVGNet as svgnet
from svgnet.util import get_root_logger, init_dist, load_checkpoint
from svgnet.data import build_dataloader, build_dataset, SVG_CATEGORIES


category2color = {item["id"]: item["color"] for item in SVG_CATEGORIES}


def get_args():
    parser = argparse.ArgumentParser("svgnet")
    parser.add_argument(
        "--config",
        type=str,
        help="path to config file",
        default="configs/svg/svg_pointT.yaml",
    )
    parser.add_argument(
        "--checkpoint",
        type=str,
        help="path to checkpoint",
        default="./best.pth",
    )
    parser.add_argument("--seed", type=int, default=2000)
    parser.add_argument(
        "--out",
        type=str,
        help="directory for output results",
        default="./output",
    )
    parser.add_argument("--save_lite", action="store_true")
    args = parser.parse_args()
    return args


def reconstruct_svg(svg_file, estimated_contents, output_folder):
    tree = ET.parse(svg_file)
    root = tree.getroot()
    ns = root.tag[:-3]
    id = 0
    for g in root.iter(ns + "g"):
        for _path in chain(
            g.iter(ns + "path"), g.iter(ns + "circle"), g.iter(ns + "ellipse")
        ):
            _path.attrib["semanticId"] = str(
                estimated_contents[id]["semanticId"]
            )
            _path.attrib["instanceId"] = str(
                estimated_contents[id]["instanceId"]
            )
            if estimated_contents[id]["semanticId"] == 0:
                _path.attrib["stroke"] = "rgb(0,0,0)"
            else:
                _path.attrib["stroke"] = (
                    f'rgb({category2color[estimated_contents[id]["semanticId"]][0]},{category2color[estimated_contents[id]["semanticId"]][1]},{category2color[estimated_contents[id]["semanticId"]][2]})'
                )
            id += 1
            pass

    tree.write(os.path.join(output_folder, os.path.basename(svg_file)))


def process():
    args = get_args()
    cfg_txt = open(args.config, "r").read()
    cfg = Munch.fromDict(yaml.safe_load(cfg_txt))
    logger = get_root_logger()
    model = svgnet(cfg.model).cuda()
    logger.info(f"Load state dict from {args.checkpoint}")
    load_checkpoint(args.checkpoint, logger, model)

    val_set = build_dataset(cfg.data.test, logger)
    dataloader = build_dataloader(
        args, val_set, training=False, dist=False, **cfg.dataloader.test
    )
    instance_eval = InstanceEval(
        num_classes=cfg.model.semantic_classes, ignore_label=35, gpu_num=1
    )
    with torch.no_grad():
        model.eval()
        for i, batch in enumerate(tqdm(dataloader)):
            json_file = batch[-1][0]
            svg_file = os.path.join(
                "./dataset/test/test/svg_gt",
                os.path.basename(json_file).replace("json", "svg"),
            )
            batch = batch[:-1]
            torch.cuda.empty_cache()
            with torch.cuda.amp.autocast(enabled=cfg.fp16):
                res = model(batch, return_loss=False)

            if args.out:
                os.makedirs(args.out, exist_ok=True)
                instances = [
                    len(instance["masks"]) for instance in res["instances"]
                ]
                if len(instances) == 0:
                    continue
                num = max(instances)
                estimated_contents = [
                    {
                        "instanceId": 0,
                        "semanticId": 0,
                    }
                ] * num
                for index, instance in enumerate(instances):
                    src_label = instance["labels"]
                    src_score = instance["scores"]
                    if src_label == instance_eval.ignore_label:
                        continue
                    if src_score < instance_eval.min_obj_score:
                        continue

                    for i in np.where(instance["masks"])[0]:
                        estimated_contents[i] = {
                            "instanceId": index + 1,
                            "semanticId": instance["labels"],
                        }

                reconstruct_svg(svg_file, estimated_contents, args.out)


if __name__ == "__main__":
    process()

```

**Comment by jjqtony** [comment]
> hello, can you try this? I'm not sure if it's right. It will estimate the semantic id and instance id, and change the color of corresponding path in svg.
> 
> import argparse
> import glob
> from itertools import chain
> import json
> import math
> import os
> import re
> import time
> import xml.etree.ElementTree as ET
> from collections import defaultdict
> 
> import mmcv
> import numpy as np
> import torch
> from tqdm import tqdm
> import yaml
> from munch import Munch
> from svgpathtools import parse_path
> 
> from svgnet.evaluation.point_wise_eval import InstanceEval
> from svgnet.model.svgnet import SVGNet as svgnet
> from svgnet.util import get_root_logger, init_dist, load_checkpoint
> from svgnet.data import build_dataloader, build_dataset, SVG_CATEGORIES
> 
> 
> category2color = {item["id"]: item["color"] for item in SVG_CATEGORIES}
> 
> 
> def get_args():
>     parser = argparse.ArgumentParser("svgnet")
>     parser.add_argument(
>         "--config",
>         type=str,
>         help="path to config file",
>         default="configs/svg/svg_pointT.yaml",
>     )
>     parser.add_argument(
>         "--checkpoint",
>         type=str,
>         help="path to checkpoint",
>         default="./best.pth",
>     )
>     parser.add_argument("--seed", type=int, default=2000)
>     parser.add_argument(
>         "--out",
>         type=str,
>         help="directory for output results",
>         default="./output",
>     )
>     parser.add_argument("--save_lite", action="store_true")
>     args = parser.parse_args()
>     return args
> 
> 
> def reconstruct_svg(svg_file, estimated_contents, output_folder):
>     tree = ET.parse(svg_file)
>     root = tree.getroot()
>     ns = root.tag[:-3]
>     id = 0
>     for g in root.iter(ns + "g"):
>         for _path in chain(
>             g.iter(ns + "path"), g.iter(ns + "circle"), g.iter(ns + "ellipse")
>         ):
>             _path.attrib["semanticId"] = str(
>                 estimated_contents[id]["semanticId"]
>             )
>             _path.attrib["instanceId"] = str(
>                 estimated_contents[id]["instanceId"]
>             )
>             if estimated_contents[id]["semanticId"] == 0:
>                 _path.attrib["stroke"] = "rgb(0,0,0)"
>             else:
>                 _path.attrib["stroke"] = (
>                     f'rgb({category2color[estimated_contents[id]["semanticId"]][0]},{category2color[estimated_contents[id]["semanticId"]][1]},{category2color[estimated_contents[id]["semanticId"]][2]})'
>                 )
>             id += 1
>             pass
> 
>     tree.write(os.path.join(output_folder, os.path.basename(svg_file)))
> 
> 
> def process():
>     args = get_args()
>     cfg_txt = open(args.config, "r").read()
>     cfg = Munch.fromDict(yaml.safe_load(cfg_txt))
>     logger = get_root_logger()
>     model = svgnet(cfg.model).cuda()
>     logger.info(f"Load state dict from {args.checkpoint}")
>     load_checkpoint(args.checkpoint, logger, model)
> 
>     val_set = build_dataset(cfg.data.test, logger)
>     dataloader = build_dataloader(
>         args, val_set, training=False, dist=False, **cfg.dataloader.test
>     )
>     instance_eval = InstanceEval(
>         num_classes=cfg.model.semantic_classes, ignore_label=35, gpu_num=1
>     )
>     with torch.no_grad():
>         model.eval()
>         for i, batch in enumerate(tqdm(dataloader)):
>             json_file = batch[-1][0]
>             svg_file = os.path.join(
>                 "./dataset/test/test/svg_gt",
>                 os.path.basename(json_file).replace("json", "svg"),
>             )
>             batch = batch[:-1]
>             torch.cuda.empty_cache()
>             with torch.cuda.amp.autocast(enabled=cfg.fp16):
>                 res = model(batch, return_loss=False)
> 
>             if args.out:
>                 os.makedirs(args.out, exist_ok=True)
>                 instances = [
>                     len(instance["masks"]) for instance in res["instances"]
>                 ]
>                 if len(instances) == 0:
>                     continue
>                 num = max(instances)
>                 estimated_contents = [
>                     {
>                         "instanceId": 0,
>                         "semanticId": 0,
>                     }
>                 ] * num
>                 for index, instance in enumerate(instances):
>                     src_label = instance["labels"]
>                     src_score = instance["scores"]
>                     if src_label == instance_eval.ignore_label:
>                         continue
>                     if src_score < instance_eval.min_obj_score:
>                         continue
> 
>                     for i in np.where(instance["masks"])[0]:
>                         estimated_contents[i] = {
>                             "instanceId": index + 1,
>                             "semanticId": instance["labels"],
>                         }
> 
>                 reconstruct_svg(svg_file, estimated_contents, args.out)
> 
> 
> if __name__ == "__main__":
>     process()

get error when executing your code:
    Traceback (most recent call last):
      File "visualtest.py", line 146, in <module>
        process()
      File "visualtest.py", line 129, in process
        src_label = instance["labels"]
    TypeError: 'int' object is not subscriptable

How to fix it?

**Comment by jjqtony** [comment]
> hello, can you try this? I'm not sure if it's right. It will estimate the semantic id and instance id, and change the color of corresponding path in svg.
> 

> def process():
>     args = get_args()
>     cfg_txt = open(args.config, "r").read()
>     cfg = Munch.fromDict(yaml.safe_load(cfg_txt))
>     logger = get_root_logger()
>     model = svgnet(cfg.model).cuda()
>     logger.info(f"Load state dict from {args.checkpoint}")
>     load_checkpoint(args.checkpoint, logger, model)
> 
>     val_set = build_dataset(cfg.data.test, logger)
>     dataloader = build_dataloader(
>         args, val_set, training=False, dist=False, **cfg.dataloader.test
>     )
>     instance_eval = InstanceEval(
>         num_classes=cfg.model.semantic_classes, ignore_label=35, gpu_num=1
>     )
>     with torch.no_grad():
>         model.eval()
>         for i, batch in enumerate(tqdm(dataloader)):
>             json_file = batch[-1][0]
>             svg_file = os.path.join(
>                 "./dataset/test/test/svg_gt",
>                 os.path.basename(json_file).replace("json", "svg"),
>             )
>             batch = batch[:-1]
>             torch.cuda.empty_cache()
>             with torch.cuda.amp.autocast(enabled=cfg.fp16):
>                 res = model(batch, return_loss=False)
> 
>             if args.out:
>                 os.makedirs(args.out, exist_ok=True)
>                 instances = [
>                     len(instance["masks"]) for instance in res["instances"]
>                 ]
>                 if len(instances) == 0:
>                     continue
>                 num = max(instances)
>                 estimated_contents = [
>                     {
>                         "instanceId": 0,
>                         "semanticId": 0,
>                     }
>                 ] * num
>                 for index, instance in enumerate(instances):
>                     **src_label = instance["labels"]
>                     src_score = instance["scores"]**
>                     if src_label == instance_eval.ignore_label:
>                         continue
>                     if src_score < instance_eval.min_obj_score:
>                         continue
> 
>                     for i in np.where(instance["masks"])[0]:
>                         estimated_contents[i] = {
>                             "instanceId": index + 1,
>                             "semanticId": instance["labels"],
>                         }
> 
>                 reconstruct_svg(svg_file, estimated_contents, args.out)
> 
> 
> if __name__ == "__main__":
>     process()

get error:
  Traceback (most recent call last):
    File "****", line 146, in <module>
      process()
    File "****", line 129, in process
      src_label = instance["labels"]
  TypeError: 'int' object is not subscriptable

How to fix it?

**Comment by NGGravity** [comment]
> I would like to see the visual results. However, it seems that the `test.py` file has a section for saving results but it's not implemented yet. Do you have any advice on how to show the images with detections?
> 
> Thank you in advance, and I really appreciate your work.

hi，do you resolve this issue？
